---
  - name: Playbook
    hosts: webserver
    become: yes
    become_user: root
    tasks:
      - name: pull an image
        docker_image:
          name: adhi100doc/react-docker-123
          tag: latest
          source: pull