---
  - name: Playbook
    hosts: webserver
    become: yes
    become_user: root
    tasks:
      - name: pull an image
        docker_image:
          name: adhi100doc/react-docker-123
          tag: latest
          source: pull
      - name: Create container
        docker_container:
          name: react-project
          image: adhi100doc/react-docker-123:latest
          state: present
          recreate: yes
          ports:
           - "8080:9000"
      - name: Run data container
        docker_container:
          name: react-project
          image: adhi100doc/react-docker-123:latest
          state: started
